# Generated by Django 3.2.3 on 2021-05-16 12:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareConditionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fare_condition', models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('business', 'Business')], max_length=10)),
                ('coef', models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='seat',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='transportation.aircraft'),
        ),
    ]
