# Generated by Django 3.2.3 on 2021-05-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_auto_20210516_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
